import './globals.css';
import type { Metadata } from 'next';
import { Roboto_Slab } from 'next/font/google';
import Header from './Components/Header';
import ThemeWrapper from './Theme';
const robotoSlab = Roboto_Slab({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${robotoSlab.className}  bg-gray-100 text-black  
        dark:bg-black dark:text-white capitalize`}
      >
        <ThemeWrapper>
          <Header />
          <main className="mt-5">{children}</main>
        </ThemeWrapper>
      </body>
    </html>
  );
}
