import './globals.css';
import type { Metadata } from 'next';
import { Roboto_Slab } from 'next/font/google';
import Header from './Components/Header';
import ThemeWrapper from './Theme';
import ReactQueryPvorider from './StateManagement/Provider';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import { Zoom } from 'react-toastify';
const robotoSlab = Roboto_Slab({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${robotoSlab.className}  bg-gray-100 text-black  
        dark:bg-black dark:text-white capitalize`}
      >
        <ReactQueryPvorider>
          <ThemeWrapper>
            <Header />
            <main className=" mt-20">{children}</main>
            <ToastContainer
              draggablePercent={60}
              transition={Zoom}
              position="top-center"
              autoClose={2000}
              hideProgressBar={false}
              newestOnTop={false}
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
            />
          </ThemeWrapper>
        </ReactQueryPvorider>
      </body>
    </html>
  );
}
